export const FETCH_TOTAL_FEES_REQUEST = 'FETCH_TOTAL_FEES_REQUEST';
export const FETCH_TOTAL_FEES_SUCCESS = 'FETCH_TOTAL_FEES_SUCCESS';
export const FETCH_TOTAL_FEES_FAILURE = 'FETCH_TOTAL_FEES_FAILURE';

export const FETCH_TOTAL_FEES_STANDARD_WISE_REQUEST = 'FETCH_TOTAL_FEES_STANDARD_WISE_REQUEST';
export const FETCH_TOTAL_FEES_STANDARD_WISE_SUCCESS = 'FETCH_TOTAL_FEES_STANDARD_WISE_SUCCESS';
export const FETCH_TOTAL_FEES_STANDARD_WISE_FAILURE = 'FETCH_TOTAL_FEES_STANDARD_WISE_FAILURE';
