export const FETCH_STUDENT_LIST_REQUEST = 'FETCH_STUDENT_LIST_REQUEST';
export const FETCH_STUDENT_LIST_SUCCESS = 'FETCH_STUDENT_LIST_SUCCESS';
export const FETCH_STUDENT_LIST_FAILURE = 'FETCH_STUDENT_LIST_FAILURE';

export const FETCH_ADD_STUDENT_REQUEST = 'FETCH_ADD_STUDENT_REQUEST';
export const FETCH_ADD_STUDENT_SUCCESS = 'FETCH_ADD_STUDENT_SUCCESS';
export const FETCH_ADD_STUDENT_FAILURE = 'FETCH_ADD_STUDENT_FAILURE';

export const FETCH_DELETE_STUDENT_REQUEST = 'FETCH_DELETE_STUDENT_REQUEST';
export const FETCH_DELETE_STUDENT_SUCCESS = 'FETCH_DELETE_STUDENT_SUCCESS';
export const FETCH_DELETE_STUDENT_FAILURE = 'FETCH_DELETE_STUDENT_FAILURE';

export const FETCH_STUDENT_DETAIL_REQUEST = 'FETCH_STUDENT_DETAIL_REQUEST';
export const FETCH_STUDENT_DETAIL_SUCCESS = 'FETCH_STUDENT_DETAIL_SUCCESS';
export const FETCH_STUDENT_DETAIL_FAILURE = 'FETCH_STUDENT_DETAIL_FAILURE';

export const FETCH_UPDATE_STUDENT_REQUEST = 'FETCH_UPDATE_STUDENT_REQUEST';
export const FETCH_UPDATE_STUDENT_SUCCESS = 'FETCH_UPDATE_STUDENT_SUCCESS';
export const FETCH_UPDATE_STUDENT_FAILURE = 'FETCH_UPDATE_STUDENT_FAILURE';
