export const FETCH_STANDARD_LIST_REQUEST = 'FETCH_STANDARD_LIST_REQUEST';
export const FETCH_STANDARD_LIST_SUCCESS = 'FETCH_STANDARD_LIST_SUCCESS';
export const FETCH_STANDARD_LIST_FAILURE = 'FETCH_STANDARD_LIST_FAILURE';

export const FETCH_ADD_STANDARD_REQUEST = 'FETCH_ADD_STANDARD_REQUEST';
export const FETCH_ADD_STANDARD_SUCCESS = 'FETCH_ADD_STANDARD_SUCCESS';
export const FETCH_ADD_STANDARD_FAILURE = 'FETCH_ADD_STANDARD_FAILURE';

export const FETCH_DELETE_STANDARD_REQUEST = 'FETCH_DELETE_STANDARD_REQUEST';
export const FETCH_DELETE_STANDARD_SUCCESS = 'FETCH_DELETE_STANDARD_SUCCESS';
export const FETCH_DELETE_STANDARD_FAILURE = 'FETCH_DELETE_STANDARD_FAILURE';

export const FETCH_STANDARD_DETAIL_REQUEST = 'FETCH_STANDARD_DETAIL_REQUEST';
export const FETCH_STANDARD_DETAIL_SUCCESS = 'FETCH_STANDARD_DETAIL_SUCCESS';
export const FETCH_STANDARD_DETAIL_FAILURE = 'FETCH_STANDARD_DETAIL_FAILURE';

export const FETCH_UPDATE_STANDARD_REQUEST = 'FETCH_UPDATE_STANDARD_REQUEST';
export const FETCH_UPDATE_STANDARD_SUCCESS = 'FETCH_UPDATE_STANDARD_SUCCESS';
export const FETCH_UPDATE_STANDARD_FAILURE = 'FETCH_UPDATE_STANDARD_FAILURE';
